objects/ServiceRequest__c.object
<CustomObject>
    <label>Service Request</label>
    <pluralLabel>Service Requests</pluralLabel>
    <nameField>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
        <displayFormat>SR-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
    </fields>
</CustomObject>

classes/ServiceRequestTriggerHandler.cls
public class ServiceRequestTriggerHandler {
    public static void onAfterUpdate(List<ServiceRequest__c> newList, Map<Id, ServiceRequest__c> oldMap) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for (ServiceRequest__c sr : newList) {
            ServiceRequest__c oldSr = oldMap.get(sr.Id);
            if (sr.Status__c != oldSr.Status__c) {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {sr.CustomerEmail__c});
                email.setSubject('Service Request Status Update');
                email.setPlainTextBody('Your service request status has been updated to ' + sr.Status__c);
                emails.add(email);
                sr.StatusHistory__c += '\n' + sr.Status__c + ' - ' + System.now();
            }
        }
        if (!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }
    }
}