objects/Service_Request__c.object
<CustomObject>
    <label>Service Request</label>
    <pluralLabel>Service Requests</pluralLabel>
    <nameField>
        <label>Service Request Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
    </fields>
</CustomObject>

classes/ServiceRequestController.cls
public with sharing class ServiceRequestController {
    @AuraEnabled
    public static void createServiceRequest(String name, String email, String phone, String description, String priority) {
        Service_Request__c serviceRequest = new Service_Request__c();
        serviceRequest.Name__c = name;
        serviceRequest.Email__c = email;
        serviceRequest.Phone__c = phone;
        serviceRequest.Description__c = description;
        serviceRequest.Priority__c = priority;
        insert serviceRequest;
        // Send email confirmation logic here
    }
}